# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VHDL/Ex_1/Ex_1.cache/wt [current_project]
set_property parent.project_path F:/VHDL/Ex_1/Ex_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib F:/VHDL/Ex_1/Ex_1.srcs/sources_1/new/Ex_1.v
synth_design -top Ex_1 -part xc7a100tfgg484-1
write_checkpoint -noxdef Ex_1.dcp
catch { report_utilization -file Ex_1_utilization_synth.rpt -pb Ex_1_utilization_synth.pb }
