# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/VHDL/Ex_2/ip/xorgate_0/xorgate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xorgate_0 || ORIG_REF_NAME==xorgate_0}]

# IP: F:/VHDL/Ex_2/ip/orgate_0/orgate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==orgate_0 || ORIG_REF_NAME==orgate_0}]

# IP: F:/VHDL/Ex_2/ip/notgate_0/notgate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==notgate_0 || ORIG_REF_NAME==notgate_0}]

# IP: F:/VHDL/Ex_2/ip/muxnto1_0/muxnto1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==muxnto1_0 || ORIG_REF_NAME==muxnto1_0}]

# IP: F:/VHDL/Ex_2/ip/barrelshifter8_0_1/barrelshifter8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==barrelshifter8_0 || ORIG_REF_NAME==barrelshifter8_0}]

# IP: F:/VHDL/Ex_2/ip/andgate_0/andgate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==andgate_0 || ORIG_REF_NAME==andgate_0}]

# IP: F:/VHDL/Ex_2/ip/addsub_0/addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==addsub_0 || ORIG_REF_NAME==addsub_0}]
